# for local development
version: '3.3'
services:
  frontend:
    build:
      context: .
      # target: 'develop-stage'
    ports:
    - '8090:8080'
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn serve"